### ISSUE TITLE
Please explain the sensor result for a dummy like me :-)

### ISSUE THREAD

**Issue by fribse** [custom-components/sensor.unifigateway#15]
I have created a sensor with this very cool custom component, and I get all the nice results like:

```
sensor.unifi_gateway_wan
OK
subsystem: wan num_gw: 1
num_adopted: 1
num_disconnected: 0
num_pending: 0
status: ok
wan_ip: x.x.x.x
gateways: x.x.x.x
netmask: 255.255.255.128
nameservers: 127.0.0.1
num_sta: 78
tx_bytes-r: 65571
rx_bytes-r: 72117
gw_mac: x.x.x.x.x.x.x.x
gw_name: null
gw_system-stats:
  cpu: '1'
  mem: '6'
  temps:
    Board (CPU): 52 C
    Board (PHY): 51 C
    CPU: 73 C
    PHY: 73 C
uptime: '133007'
gw_version: 4.4.50.5272479
friendly_name: UniFi Gateway WAN
icon: mdi:shield-outline

```

I have created this template for pulling the temperature:
`
{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['temps']['CPU'].split(' ')[0] | int }}
`
And that gives me a number of 73, but what does the 'Board (CPU)' and 'Board (PHY)' and 'PHY' mean, is it the right temperature I'm pulling out of it?
