### ISSUE TITLE
After Update to 3.2 - no Sensor?

### ISSUE THREAD

**Issue by schmidiij** [custom-components/sensor.unifigateway#38]
i update with HACS the Component to 3.2.
After this all sensor are disappeared?

my config is:
```
- platform: unifigateway
  host: 10.10.100.5
  username: admin
  password: xxxxxx
  monitored_conditions:
    - wlan
    - firmware
    - wan
```

![image](https://user-images.githubusercontent.com/29889802/113392686-ccc7fa00-9395-11eb-987c-369bc2bf5513.png)

How is the sensor now named?
