### ISSUE TITLE
UCK 6.1.71: Changes in webinterface and 404

### ISSUE THREAD

**Issue by AlfaJackal** [custom-components/sensor.unifigateway#41]
Hi,

just a quick heads up (and reaching out for a quick fix if possible): 
The newest UCK-Software has some changes so the unifigateway wont connect with port 443.
```
Logger: custom_components.unifigateway.sensor
Source: custom_components/unifigateway/sensor.py:91 
Integration: unifigateway (documentation) 
First occurred: 12:03:18 PM (1 occurrences) 
Last logged: 12:03:18 PM

Failed to connect to Unifi Security Gateway: Login failed - status code: 404

```

This is my config which worked perfectly until the latest UCK update:
```
#Unifi Gateway
- platform: unifigateway
  host: 10.0.0.2
  port: 443
  username: !secret unifi_user_ro
  password: !secret unifi_password_ro
  monitored_conditions:
    - www
    - wlan
    - alerts
    - firmware
    - vpn
    - wan

```

I think it might just a small adaption of the url. As you can see, `.../network/...` has been added. 
![image](https://user-images.githubusercontent.com/17096950/116680497-09ded680-a9ac-11eb-846a-c700a2ec061b.jpeg)

Any chances for me to fix it? I would really appreciate a small snippet.
