### ISSUE TITLE
Need Help for sensor unifigateway

### ISSUE THREAD

**Issue by rto54** [custom-components/sensor.unifigateway#42]
Hi,
I try to configure the HACS integration unifigateway with sensor.unifigateway

But it doesn’t work.

I have a UDM Pro with the latest firmware version

I configurer the sensor as indicated in the doc

Copy to clipboard
- platform: unifigateway
    host: 192.168.X.X
    port: 443
    username: rodolphe
    password: XXXXXXXXX
    verify_ssl: false
    monitored_conditions:
      - wwwJ'ai configuré le senso
      - wan
      - lan
      - wlan
      - alerts
      - firmware

![image](https://user-images.githubusercontent.com/20343636/118399181-3bb69500-b65c-11eb-9273-ce89b7e59306.png)

Thank you in advance for your help

**Comment by gislis2** [comment]
Did you add it to your configuration.yaml ? (or sensors.yaml)

I have UDM and works with this:
```yaml
- platform: unifigateway
  host: !secret unifi_url
  port: 443
  version: UDMP-unifiOS
  username: !secret unifi_username
  password: !secret unifi_password
  monitored_conditions:
    - vpn
    - www
    - lan
    - wan
    - wlan
    - alerts
```

Couldn't get the firmware thingy to work so I removed that option
