### ISSUE TITLE
Multiple sites changing sensor IDs at reboot

### ISSUE THREAD

**Issue by rucknapucknavitz** [custom-components/sensor.unifigateway#48]
I have two sites and so have set my configuration as follows:

```
## UNIFI SENSORS
# UniFi Gateway - Site 1
  - platform: unifigateway
    host: 192.168.1.175
    port: 8443
    username: !secret unifi_username
    password: !secret unifi_password
    monitored_conditions:
      - www
      - wan
      - lan
      - wlan
      - alerts
      - firmware
      #- vpn

# UniFi Gateway - Site 2
  - platform: unifigateway
    host: 192.168.1.175
    port: 8443
    site_id: !secret unifi_site_id
    username: !secret unifi_username
    password: !secret unifi_password
    monitored_conditions:
      - www
      - wan
      - lan
      - wlan
      - alerts
      - firmware
      #- vpn
```

The sensors then populate as:
```
sensor.unifi_gateway_wan
sensor.unifi_gateway_wan_2
```

wan is not always the default (Site 1), and wan_2 is not always the Site 2 id.
Sometimes they switch, throwing off my named templates, e.g. wan somtimes maps to Default (Site 1) and sometimes to Site 2.

Is there a way, using a friendly name or otherwise, to always map wan to Default (Site 1) and wan_2 to Site 2?

Thanks!
