### ISSUE TITLE
No integration with UDM PRo

### ISSUE THREAD

**Issue by weemaba999** [custom-components/sensor.unifigateway#52]
Hi,

For a whole week I've been trying to setup te integration without luck. I constantly get messages that my sensors (unify gateway wan and others) are not available. I'm using a physical UDM Pro as gateway, tried using a local username and password, tried using port 443 and 8443... but without any success....

One thing I do encounter, when I log in to my console from Unifi, I got an ssl error, has this something to do with it ? 

Can you confirm right port to use ? 443 or 8443 ? Version : unifiOS, ....

Kr,

**Comment by Tamsy** [comment]
```
    - platform: unifigateway
      host: <LAN IP ADDRESS OF YOUR UDM Pro>
      port: 443
      version: UDMP-unifiOS
      username: !secret unifi_username
      password: !secret unifi_password
      monitored_conditions:
        - www
        - wan
        - wlan
        - lan
        - alerts
        - firmware
```
        
should work.

As for the sensors you certainly have to add those to your configuration.yaml, i.e.:

```
    - platform: template
      sensors:
        unifi_gateway_wired_clients:
          friendly_name: 'UDM Pro Wired Clients'
          value_template: "{{ states.sensor.unifi_gateway_lan.attributes.num_user }}"
          icon_template: mdi:lan
```

etc.
