### ISSUE TITLE
Dream Machine SE / HASIO different VLAN

### ISSUE THREAD

**Issue by lowrisk75** [custom-components/sensor.unifigateway#56]
I can't manage to connect to a Dream Machine SE while HASIO is on a different subnet.

I created the LAN_IN rules which allow HASIO_IP to access 443 PORT but same issue
regarding the user, it's a local user, which at first was view only, I temporary changed to admin, same problem

my config file is : 

```
  - platform: unifigateway
    host: 192.168.3.1
    port: 443
    version: UDMP-unifiOS
    username: username
    password: password
    monitored_conditions:
      - www
      - wan
      - wlan
      - lan
      - alerts
      - firmware
```

mDNS is enabled on both network.

I'm trying to access directly with the VLAN gateway IP but I also tried with the management IP *192.168.1.1
