### ISSUE TITLE
Unverified HTTPS request is being made to host

### ISSUE THREAD

**Issue by varadujagan** [custom-components/sensor.unifigateway#58]
**Error Message**
```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/unifigateway/sensor.py:171
Integration: unifigateway (documentation)
First occurred: 9:16:16 PM (3 occurrences)
Last logged: 10:02:16 PM

/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.10.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings warnings.warn(
```

**configuration.yaml **
```
sensor:
  - platform: unifigateway
    host: 192.168.10.1
    port: 443
    version: UDMP-unifiOS
    verify_ssl: false
    username: !secret u_unifi
    password: !secret p_unifi
    monitored_conditions:
      - www
      - wan
```
I tried reinstalling the component and also tried with and without verify_ssl. I don't know what to do, I'm getting so many warning Logs. Can anyone help me with this
